export const dict = {
    en:{
        layout:{
            nav_item_1:"Our work",
            nav_item_2:"Achievements",
            nav_item_3:"Services",
            nav_item_4:"Technologies",
            nav_item_5:"Team",
            nav_item_6:"Contact",
            theme_tooltip_1:"Theme",
            lang_tooltip_1:"Language",
            social_tooltip_1:"Facebook",
            social_tooltip_2:"Github",
            social_tooltip_3:"Instagram",
            section_title_1:"profesional team",
            article_title_1:"We just create your dream app",
            article_text_1:"We are your best alternative on software development, with high quality products that shines in intuitive, design, speed and originality.",
            article_action_1:"Let's talk",
            privacy_policy:"Privacy Policy",
            terms_of_use:"Terms of Use",
            rights:"© 2024 Husky Devs. All rights reserved.",
        },
        section_0:{
            section_title:"profesional team",
            article_title:"We just create your dream app",
            article_text:"We are your best alternative on software development, with high quality products that shines in intuitive, design, speed and originality.",
            article_button:"Let's talk"
        },
        section_1:{
            section_title:"Our work",
            article_title:"We create your dream app",
            card_title_0:"Raffle website demo",
            card_description_0:"Demo of the raffle website for clients",
            card_title_1:"Gana con Ivan",
            card_description_1:"Raffle website",
            card_title_2:"Russa Fortuna",
            card_description_2:"Raffle website",
            card_title_3:"Gana con el Guerrero",
            card_description_3:"Raffle website",
            card_title_4:"Libling Solutions",
            card_description_4:"Travel to Luxembourg",
            card_title_5:"Global Rifas",
            card_description_5:"Raffle website",
            card_title_6:"Keicash",
            card_description_6:"Raffle website",
            card_title_7:"Gana con Andrea",
            card_description_7:"Raffle website",
            card_title_8:"Gana con Kadi CCS",
            card_description_8:"Raffle website",
            card_title_9:"Vergacion de Rifa",
            card_description_9:"Raffle website",
            card_button_1:"Github",
            card_button_2:"Live demo",
            card_button_3:"Show more",
            card_button_4:"Show less",
        },
        section_2:{
            section_title:"achievements",
            article_title:"We've been turning ideas into reality for over 4 years",
            article_text:"We are committed to providing our clients with the highest quality of service, from initial consultation to ongoing support.",
            card_unit_1:"years",
            card_title_1:"Experience",
            card_title_2:"Technologies",
            card_title_3:"Projects",
        },
        section_3:{
            section_title:"services",
            article_title:"Your vision, our technology",
            article_text:"We create custom mobile and web applications that perfectly fit the unique needs of your business.",
            article_extra:"We provide support in all our services",
            card_title_1:"Service API",
            card_description_1:"We develop your server application to be consumed by your client solution.",
            card_title_2:"Web service",
            card_description_2:"Shape your identity on the Internet with your own website, to contact customers and services.",
            card_title_3:"Native application",
            card_description_3:"Custom mobile apps for iOS and Android devices.",
        },
        section_4: {
            article_title: "Technologies We Have Worked with",
            list_title_1:"Front - end",
            list_item_1_1:"HTML",
            list_item_1_2:"SASS",
            list_item_1_3:"JavaScript",
            list_item_1_4:"React",
            list_item_1_5:"CSS",
            list_item_1_6:"Bootstrap",
            list_item_1_7:"Vue",
            list_item_1_8:"Angular",
            list_title_2:"Back - end",
            list_item_2_1:"Node JS",
            list_item_2_2:"Laravel",
            list_item_2_3:"Django",
            list_item_2_4:"MongoDB",
            list_item_2_5:"PHP",
            list_item_2_6:"Python",
            list_item_2_7:"MySQL",
            list_item_2_8:"Posgress SQL",
        },
        section_5: {
            article_title: "Meet our team",
            article_text: "Our experienced developers and designers are passionate about creating innovative solutions that help businesses grow.",
            team_title_0: "Fullstack Developer",
            team_description_0: "30 years old, web developer technology enthusiast focused on computers, gamer at heart and dedicated to finding the best solutions.",
            team_title_1: "Fullstack Developer",
            team_description_1: "29 years old, Web developer focused on improve everyday. Loving soccer, videogames, coding and cook.",
            team_title_2: "Business Leader",
            team_description_2: "Industrial Engineer focused on offering unique experiences and effective solutions.",
            team_title_3: "UX / UI designer",
            team_description_3: "I'm always looking for the next game-changing user experience that sparks my curiosity.",
            team_title_4: "Frontend Developer",
            team_description_4: "28 years old. Systems engineer. Living one day at a time.",
            team_title_5: "Fullstack Developer",
            team_description_5: "Software engineer with a fascination for solving problems and optimizing solutions.",
        },
        section_6: {
            section_title: "Contact",
            article_title: "Let's meet today to talk about your project",
            article_image: "Husky’s calling",
            article_text: "A member of our team will be happy to answer your questions and help you.",
            article_button: "Let’s meet"
        },
        terms:{
            title:"Terms and Conditions",
            update: 'Last updated: July 15, 2025',
            section_title_1: "Regarding Online Raffle Management Systems",
            paragraph_1: "At Husky Devs, we specialize exclusively in the development of innovative software solutions for the management and operation of online raffle platforms. It is important to clarify that we are not raffle operators, betting houses, nor organizing, promoting, or managing entities of any kind of public or private raffle or lottery.",
            paragraph_2: "Our activity is strictly limited to the design, development, implementation, and maintenance of technological tools (software) that allow third parties to manage their own raffles. Under no circumstances do we participate in the administration, execution, regulation, collection, or delivery of prizes associated with raffles operated by our clients.",
            section_title_2: "User Responsibility and Regulatory Compliance",
            paragraph_3: "We inform our clients and users that the operation of raffles in the Bolivarian Republic of Venezuela is subject to current legislation and regulation by the National Lottery Commission (CONALOT), as well as other competent authorities.",
            paragraph_4: "It is the sole responsibility of our clients and the operators of raffle platforms to ensure that their raffle activities fully and strictly comply with all laws, regulations, decrees, permits, and licenses required by CONALOT and any other applicable governmental authority in Venezuela or in the jurisdictions where they operate. This includes, but is not limited to, obtaining the necessary authorizations, paying taxes, managing prizes, protecting personal data, and any other legal obligation.",
            paragraph_5: "Husky Devs is not responsible for non-compliance with legal regulations by our clients or operators using our software. Any sanction, fine, litigation, or legal issue arising from the operation of raffles by our clients is their sole and exclusive responsibility.",
            paragraph_6: "By using our software development services, clients acknowledge and accept this limitation of liability and agree to indemnify and hold Husky Devs harmless from any claim, loss, damage, liability, cost, or expense (including attorney's fees) arising from their operation of raffles or their non-compliance with applicable regulations.",
            section_title_3: "Contact",
            paragraph_7: "If you have any questions about this disclaimer, please contact us at ",
            paragraph_7_mailto: "huskydevsteam@gmail.com"
        }  
    },
    es:{
        layout: {
            nav_item_1: "Nuestro trabajo",
            nav_item_2: "Logros",
            nav_item_3: "Servicios",
            nav_item_4: "Tecnologías",
            nav_item_5: "Equipo",
            nav_item_6: "Contacto",
            theme_tooltip_1: "Tema",
            lang_tooltip_1: "Idioma",
            social_tooltip_1: "Facebook",
            social_tooltip_2: "Github",
            social_tooltip_3: "Instagram",
            section_title_1: "equipo profesional",
            article_title_1: "Creamos tu aplicación soñada",
            article_text_1: "Somos tu mejor alternativa en desarrollo de software, con productos de alta calidad que destacan en intuición, diseño, velocidad y originalidad.",
            article_action_1: "Hablemos",
            privacy_policy: "Política de Privacidad",
            terms_of_use: "Términos de Uso",
            rights: "© 2024 Husky Devs. Todos los derechos reservados.",
        },
        section_0: {
            section_title: "equipo profesional",
            article_title: "Creamos tu aplicación soñada",
            article_text: "Somos tu mejor alternativa en desarrollo de software, con productos de alta calidad que destacan en intuición, diseño, velocidad y originalidad.",
            article_button: "Hablemos"
        },
        section_1: {
            section_title: "Nuestro trabajo",
            article_title: "Creamos la aplicación de tus sueños",
            card_title_0:"Demo del sistema de rifas",
            card_description_0:"Sistema de rifas online, version demostración para clientes",
            card_title_1:"Gana con Ivan",
            card_description_1:"Sitio web de rifas",
            card_title_2:"Russa Fortuna",
            card_description_2:"Sitio web de rifas",
            card_title_3:"Gana con el Guerrero",
            card_description_3:"Sitio web de rifas",
            card_title_4:"Libling Solutions",
            card_description_4:"Viaje a Luxemburgo",
            card_title_5:"Global Rifas",
            card_description_5:"Sitio web de rifas",
            card_title_6:"Keicash",
            card_description_6:"Sitio web de rifas",
            card_title_7:"Gana con Andrea",
            card_description_7:"Sitio web de rifas",
            card_title_8:"Gana con Kadi CCS",
            card_description_8:"Sitio web de rifas",
            card_title_9:"Vergacion de Rifa",
            card_description_9:"Sitio web de rifas",
            card_button_1: "Github",
            card_button_2: "Demo en vivo",
            card_button_3: "Mostrar más",
            card_button_4: "Mostrar menos",
            },
        section_2: {
            section_title: "Logros",
            article_title: "Hemos estado convirtiendo ideas en realidad por más de 4 años",
            article_text: "Estamos comprometidos en brindar a nuestros clientes el más alto nivel de servicio, desde la consulta inicial hasta el soporte continuo.",
            card_unit_1: "años",
            card_title_1: "Experiencia",
            card_title_2: "Tecnologías",
            card_title_3: "Proyectos",
            },
        section_3: {
            section_title: "Servicios",
            article_title: "Tu visión, nuestra tecnología",
            article_text: "Creamos aplicaciones móviles y web personalizadas que se ajustan perfectamente a las necesidades únicas de tu negocio.",
            article_extra: "Brindamos soporte en todos nuestros servicios",
            card_title_1: "Servicio API",
            card_description_1: "Desarrollamos tu aplicación de servidor para que sea consumida por tu solución cliente.",
            card_title_2: "Servicio web",
            card_description_2: "Da forma a tu identidad en Internet con tu propio sitio web, para contactar clientes y servicios.",
            card_title_3: "Aplicación nativa",
            card_description_3: "Aplicaciones móviles personalizadas para dispositivos iOS y Android.",
            },        
        section_4: {
            article_title: "Tecnologías con las que hemos trabajado",
            list_title_1:"Front - end",
            list_item_1_1:"HTML",
            list_item_1_2:"SASS",
            list_item_1_3:"JavaScript",
            list_item_1_4:"React",
            list_item_1_5:"CSS",
            list_item_1_6:"Bootstrap",
            list_item_1_7:"Vue",
            list_item_1_8:"Angular",
            list_title_2:"Back - end",
            list_item_2_1:"Node JS",
            list_item_2_2:"Laravel",
            list_item_2_3:"Django",
            list_item_2_4:"MongoDB",
            list_item_2_5:"PHP",
            list_item_2_6:"Python",
            list_item_2_7:"MySQL",
            list_item_2_8:"Posgress SQL",
        },   
        section_5: {
            article_title: "Conoce a nuestro equipo",
            article_text: "Nuestros desarrolladores y diseñadores experimentados están apasionados por crear soluciones innovadoras que ayudan a las empresas a crecer.",
            team_title_0: "Desarrollador Fullstack",
            team_description_0: "30 años, desarrollador web entusiasta de la tecnologia enfocado a computadores, gamer de corazón y dedicado a encontrar las mejores soluciones.",
            team_title_1: "Desarrollador Fullstack",
            team_description_1: "29 años, desarrollador web enfocado en mejorar cada día. Amante del fútbol, los videojuegos, la programación y la cocina.",
            team_title_2: "Líder Comercial",
            team_description_2: "Ingeniero Industrial enfocado en ofrecer experiencias únicas y soluciones efectivas.",
            team_title_3: "Diseñador UX / UI",
            team_description_3: "Siempre estoy buscando la próxima experiencia de usuario innovadora que despierte mi curiosidad.",
            team_title_4: "Desarrollador Frontend",
            team_description_4: "29 años. Ingeniero de sistemas. Viviendo un día a la vez.",
            team_title_5: "Desarrollador Fullstack",
            team_description_5: "Ingeniero de software con fascinación por resolver problemas y optimizar soluciones.",
        },   
        section_6: {
            section_title: "Contacto",
            article_title: "Reunámonos hoy para hablar sobre tu proyecto",
            article_image: "Llamada del Husky",
            article_text: "Un miembro de nuestro equipo estará encantado de responder tus preguntas y ayudarte.",
            article_button: "Reunámonos"
        },
        terms:{
            title:"Términos y condiciones",
            update:'Última actualización: 15 de julio, 2025',
            section_title_1: "Relativo a los Sistemas de Gestión de Rifas Online",
            paragraph_1: "En Husky Devs, nos especializamos exclusivamente en el desarrollo de soluciones de software innovadoras para la gestión y operación de plataformas de rifas online. Es fundamental aclarar que no somos operadores de rifas, casas de apuestas, ni entidades organizadoras, promotoras o gestoras de ningún tipo de sorteo o rifa pública o privada.",
            paragraph_2: "Nuestra actividad se limita estrictamente al diseño, desarrollo, implementación y mantenimiento de herramientas tecnológicas (software) que permiten a terceros gestionar sus propias rifas. En ningún caso participamos en la administración, ejecución, regulación, recaudación, ni entrega de premios asociados a las rifas operadas por nuestros clientes.",
            section_title_2: "Responsabilidad del Usuario y Cumplimiento Normativo",
            paragraph_3: "Informamos a nuestros clientes y usuarios que la operación de rifas en la República Bolivariana de Venezuela está sujeta a la legislación vigente y a la regulación de la Comisión Nacional de Loterías (CONALOT), así como de otras autoridades competentes.",
            paragraph_4: "Es responsabilidad exclusiva de nuestros clientes y de los operadores de las plataformas de rifas asegurarse de que sus actividades de rifas cumplan plena y rigurosamente con todas las leyes, reglamentos, decretos, permisos y licencias requeridos por CONALOT y cualquier otra autoridad gubernamental aplicable en Venezuela o en las jurisdicciones donde operen. Esto incluye, pero no se limita a, la obtención de las autorizaciones necesarias, el pago de impuestos, la gestión de premios, la protección de datos personales y cualquier otra obligación legal.",
            paragraph_5: "Husky Devs no se hace responsable por el incumplimiento de la normativa legal por parte de nuestros clientes o de los operadores que utilizan nuestro software. Cualquier sanción, multa, litigio o problema legal derivado de la operación de rifas por parte de nuestros clientes es responsabilidad única y exclusiva de estos.",
            paragraph_6: "Al utilizar nuestros servicios de desarrollo de software, los clientes reconocen y aceptan esta limitación de responsabilidad y se comprometen a indemnizar y mantener indemne a Husky Devs de cualquier reclamo, pérdida, daño, responsabilidad, costo o gasto (incluidos los honorarios de abogados) que surja de su operación de rifas o de su incumplimiento de la normativa aplicable.",
            section_title_3: "Contacto",
            paragraph_7: "Si tiene alguna pregunta sobre este descargo de responsabilidad, por favor contáctenos a ",
            paragraph_7_mailto: "huskydevsteam@gmail.com"

        }      
    }
}